In [1]:
import numpy as np

In [4]:
def fn(x):
    print(x/x.sum())

In [6]:
def softmax(x):
    e = np.exp(x) # 확률이 높은곳에 더 가중치를 준다는 의미
    print(e)
    print( e/np.sum(e) )

In [8]:
a = np.array([2.0 ,1.0, 0.1])
print(fn(a))
softmax(a)

[0.64516129 0.32258065 0.03225806]
None
[7.3890561  2.71828183 1.10517092]
[0.65900114 0.24243297 0.09856589]
