### 조건부 확률
- B가 주어졌을 때 사건 A의 조건부 확률 

### 베이즈 정리 종류
- 가우시안 : 설명변수가 연속형인 경우
- 다항분포 : 설명변수가 범주형인 경우
- 베르누이 : 설명변수가 이분형인 경우



## 실습

### 1. 가우시안 나이브 베이즈

데이터, 모듈 불러오기

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd

In [4]:
iris = datasets.load_iris()
df_X = pd.DataFrame(iris['data'])
df_Y = pd.DataFrame(iris['target'])

- 모델 피팅

In [18]:
gnb = GaussianNB()
fitted = gnb.fit(iris.data, iris.target)
y_pred = fitted.predict(iris.data)

In [19]:
# 1,2,3,4는 0일 나올 것이다.
fitted.predict_log_proba(iris.data)[[1,2,3,4]]

array([[  0.        , -38.72865809, -56.71097803],
       [  0.        , -41.37603426, -59.01694707],
       [  0.        , -38.76127568, -56.4811533 ],
       [  0.        , -42.23775063, -58.80806896]])

In [21]:
y_pred[[1,2,3,4]]

array([0, 0, 0, 0])

- Confusion matrix 구하기

In [22]:
from sklearn.metrics import confusion_matrix

In [25]:
confusion_matrix(iris.target, y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

- Prior 설정하기
    - 많이 나올꺼 같은 범주에 수치를 높게 주면 잘 맞춘다.?

In [29]:
# 범주 수만큼 설정
gnb2 = GaussianNB(priors = [1/100,1/100,98/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_pred2 = fitted2.predict(iris.data)
confusion_matrix(iris.target, y_pred2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]], dtype=int64)

In [30]:
# 범주 수만큼 설정
gnb2 = GaussianNB(priors = [1/100,98/100,1/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_pred2 = fitted2.predict(iris.data)
confusion_matrix(iris.target, y_pred2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]], dtype=int64)

### 2. 다항분포 나이브 베이즈

In [33]:
from sklearn.naive_bayes import MultinomialNB

In [34]:
import numpy as np

In [39]:
# 0 ~ 4 까지 2차원 배열 생성 
X = np.random.randint(5, size = (6,100))
Y = np.array([1,2,3,4,5,6])

- 모델생성

In [44]:
clf = MultinomialNB()
clf_fitted = clf.fit(X,Y)

In [79]:
clf_fitted.predict_log_proba(X[[2]])

array([[-77.69047352, -98.61691664,   0.        , -75.51354133,
        -76.61198072, -85.50130482]])

- proir 변경해보기

In [68]:
# prior의 값을 높게 준 쪽으로 값으로 나온다.
clf2 = MultinomialNB(class_prior=[0.1,0.1,0.002,0.1,0.1,0.8])
clf_fitted2 = clf2.fit(X,Y)

In [80]:
clf_fitted2.predict_log_proba(X[[2]])

array([[-73.77845051, -94.70489364,   0.        , -71.60151833,
        -72.69995771, -79.50984028]])